<?php

return [
    'enabled' => env('FBR_ENABLED', false),
    'environment' => env('FBR_ENVIRONMENT', 'sandbox'),
    'sandbox_token' => env('FBR_SANDBOX_TOKEN'),
    'production_token' => env('FBR_PRODUCTION_TOKEN'),
    'timeout' => env('FBR_API_TIMEOUT', 300),
    'seller_ntn' => env('FBR_SELLER_NTN'),
    'seller_business_name' => env('FBR_SELLER_BUSINESS_NAME'),
    'seller_province' => env('FBR_SELLER_PROVINCE'),
    'seller_address' => env('FBR_SELLER_ADDRESS'),
    'default_hs_code' => env('FBR_DEFAULT_HS_CODE'),
    'default_uom' => env('FBR_DEFAULT_UOM'),
    'default_sale_type' => env('FBR_DEFAULT_SALE_TYPE', 'Goods at standard rate (default)'),
    'default_buyer_registration_type' => env('FBR_DEFAULT_BUYER_REGISTRATION_TYPE', 'Unregistered'),
    'sandbox_scenario_id' => env('FBR_SANDBOX_SCENARIO_ID'),
    'sale_types' => [
        'Goods at standard rate (default)',
        'Goods at Reduced Rate',
        'Exempt goods',
        'Goods at zero-rate',
        '3rd Schedule Goods',
        'Steel melting and re-rolling',
        'Ship breaking',
        'Telecommunication services',
        'Toll Manufacturing',
        'Petroleum Products',
        'Electricity Supply to Retailers',
        'Gas to CNG stations',
        'Mobile Phones',
        'Processing/Conversion of Goods',
        'Goods (FED in ST Mode)',
        'Services (FED in ST Mode)',
        'Services',
        'Electric Vehicle',
        'Cement /Concrete Block',
        'Potassium Chlorate',
        'CNG Sales',
        'Goods as per SRO.297(|)/2023',
        'Non-Adjustable Supplies',
    ],
    'scenarios' => [
        'SN001' => 'Goods at standard rate - registered buyer',
        'SN002' => 'Goods at standard rate - unregistered buyer',
        'SN003' => 'Steel melting and re-rolling',
        'SN004' => 'Sale by ship breakers',
        'SN005' => 'Reduced rate sale (Eighth Schedule)',
        'SN006' => 'Exempt goods sale (Sixth Schedule)',
        'SN007' => 'Zero-rated sale',
        'SN008' => 'Third Schedule goods (retail price taxation)',
        'SN009' => 'Cotton Spinners purchase from Cotton Ginners',
        'SN010' => 'Telecom services rendered or provided',
        'SN011' => 'Toll manufacturing - steel sector',
        'SN012' => 'Sale of petroleum products',
        'SN013' => 'Electricity supply to retailers',
        'SN014' => 'Sale of gas to CNG stations',
        'SN015' => 'Sale of mobile phones (Ninth Schedule)',
        'SN016' => 'Processing / conversion of goods',
        'SN017' => 'Goods where FED is charged in ST mode',
        'SN018' => 'Services where FED is charged in ST mode',
        'SN019' => 'Services rendered or provided',
        'SN020' => 'Sale of electric vehicles',
        'SN021' => 'Sale of cement / concrete block',
        'SN022' => 'Sale of potassium chlorate',
        'SN023' => 'Sale of CNG',
        'SN024' => 'Goods sold under SRO 297(I)/2023',
        'SN025' => 'Drugs at fixed ST rate (Eighth Schedule)',
        'SN026' => 'Retailer sale to end consumer - standard rate',
        'SN027' => 'Retailer sale to end consumer - 3rd Schedule',
        'SN028' => 'Retailer sale to end consumer - reduced rate',
    ],
    'reduced_rate_hs' => [
        '0102.2930' => [
            'rate' => '10%',
            'sroScheduleNo' => 'EIGHTH SCHEDULE Table 1',
            'sroItemSerialNo' => '84(i)',
        ],
        '0101.2100' => [
            'rate' => '1%',
            'sroScheduleNo' => 'EIGHTH SCHEDULE Table 1',
            'sroItemSerialNo' => '70',
        ],
    ],
    'urls' => [
        'sandbox' => [
            'validate' => 'https://gw.fbr.gov.pk/di_data/v1/di/validateinvoicedata_sb',
            'submit' => 'https://gw.fbr.gov.pk/di_data/v1/di/postinvoicedata_sb',
        ],
        'production' => [
            'validate' => 'https://gw.fbr.gov.pk/di_data/v1/di/validateinvoicedata',
            'submit' => 'https://gw.fbr.gov.pk/di_data/v1/di/postinvoicedata',
        ],
    ],
];
